export type {
  BlockActivationStatus,
  BlockPluginDefinition,
  BlockTunes,
  BlockUpdate,
  ConversionPayload,
  ConversionTarget,
  EditorBlockSnapshot,
  EditorBlocksApi,
  DeepReadonly,
  DiagnosticThresholds,
  DocumentChange,
  EditorConfig,
  EditorDiagnostic,
  EditorDiagnosticCode,
  EditorDocument,
  EditorEventMap,
  EditorEventName,
  EditorInlineWidget,
  EditorOutputData,
  EditorValidationIssue,
  EditorValidationReason,
  EditorValidationIssue,
  FocusTarget,
  IEditor,
  InlinePluginDefinition,
  InsertBlockInput,
  TextAlign,
  TransactionCommitted,
} from './publicTypes.js'

export function createEditor(config: import('./publicTypes.js').EditorConfig): import('./publicTypes.js').IEditor